name: todo_spring_2025
description: "TODO Spring 2025"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  sign_in_button: ^3.2.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.0.0
  app_settings: ^5.1.1
  timezone: ^0.10.0
  audioplayers: ^6.4.0
  share_plus: ^7.2.1
  #google_places_api: ^1.0.8
  google_places_flutter: ^2.1.0
  #http: ^1.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/todoAppDIS.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - .env

